# Generated by Django 2.1.1 on 2019-10-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20191013_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergameinfo',
            name='try_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
