# Generated by Django 2.1.1 on 2019-11-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191019_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='guessed',
            field=models.BooleanField(default=False),
        ),
    ]
